[project]
name = "Xplora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "langgraph>=0.5.4",
    "setuptools>=80.9.0",
]
